// Auth action types
export const FETCH_USER = 'FETCH_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_START = 'REGISTER_USER_START';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_START = 'LOGIN_USER_START';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';
export const LOGOUT_USER_START = 'LOGOUT_USER_START';

// Employees action types
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAIL = 'GET_EMPLOYEES_FAIL';
export const GET_EMPLOYEES_START = 'GET_EMPLOYEES_START';

export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_FAIL = 'CREATE_EMPLOYEE_FAIL';
export const CREATE_EMPLOYEE_START = 'CREATE_EMPLOYEE_START';

export const GET_EMPLOYEE_BY_ID_SUCCESS = 'GET_EMPLOYEE_BY_ID_SUCCESS';
export const GET_EMPLOYEE_BY_ID_FAIL = 'GET_EMPLOYEE_BY_ID_FAIL';
export const GET_EMPLOYEE_BY_ID_START = 'GET_EMPLOYEE_BY_ID_START';
